package me.randomhashtags.worldlaws.federal;

public enum BillStatus {
    INTRODUCED,
    COMMITTEE_CONSIDERATION,
    FLOOR_CONSIDERATION,
    FAILED_ONE_CHAMBER,
    PASSED_ONE_CHAMBER,
    PASSED_BOTH_CHAMBERS,
    RESOLVING_DIFFERENCES,
    TO_PRESIDENT,
    VETO_ACTIONS,
    BECAME_LAW,
}
