package me.randomhashtags.worldlaws.notifications;

public enum RemoteNotificationCategory {
    SOFTWARE_UPDATE_APPLE_IOS,
    SOFTWARE_UPDATE_APPLE_IPADOS,
    SOFTWARE_UPDATE_APPLE_MACOS,
    SOFTWARE_UPDATE_APPLE_WATCHOS,
    SOFTWARE_UPDATE_APPLE_TVOS,
    SOFTWARE_UPDATE_APPLE_APPLE_TV,
    SOFTWARE_UPDATE_APPLE_SAFARI,
    SOFTWARE_UPDATE_APPLE_XCODE,

    SOFTWARE_UPDATE_CONSOLE_PLAYSTATION_4,
    SOFTWARE_UPDATE_CONSOLE_PLAYSTATION_5,

    VIDEO_GAME_UPDATE,
    ;
}
