package me.randomhashtags.worldlaws.location;

public enum CountryInfo implements SovereignStateInfo {
    LEGISLATURE_TYPE,

    AGRICULTURE_FOOD_APPLE_PRODUCTION("Apple Production"),
    AGRICULTURE_FOOD_APRICOT_PRODUCTION("Apricot Production"),
    AGRICULTURE_FOOD_ARTICHOKE_PRODUCTION("Artichoke Production"),
    AGRICULTURE_FOOD_AVOCADO_PRODUCTION("Avocado Production"),
    AGRICULTURE_FOOD_CHERRY_PRODUCTION("Cherry Production"),
    AGRICULTURE_FOOD_COCONUT_PRODUCTION("Coconut Production"),
    AGRICULTURE_FOOD_COFFEE_PRODUCTION("Coffee Production"),
    AGRICULTURE_FOOD_CUCUMBER_PRODUCTION("Cucumber Production"),
    AGRICULTURE_FOOD_EGGPLANT_PRODUCTION("Eggplant Production"),
    AGRICULTURE_FOOD_GARLIC_PRODUCTION("Garlic Production"),
    AGRICULTURE_FOOD_GRAPE_PRODUCTION("Grape Production"),
    AGRICULTURE_FOOD_PAPAYA_PRODUCTION("Papaya Production"),
    AGRICULTURE_FOOD_PEAR_PRODUCTION("Pear Production"),
    AGRICULTURE_FOOD_PINEAPPLE_PRODUCTION("Pineapple Production"),
    AGRICULTURE_FOOD_PLUM_PRODUCTION("Plum Production"),
    AGRICULTURE_FOOD_POTATO_PRODUCTION("Potato Production"),
    AGRICULTURE_FOOD_SOYBEAN_PRODUCTION("Soybean Production"),
    AGRICULTURE_FOOD_TOMATO_PRODUCTION("Tomato Production"),
    AGRICULTURE_RENEWABLE_ELECTRICITY_PRODUCTION("Renewable Electricity Production"),

    AVAILABILITY_ALEXA("Alexa"),
    AVAILABILITY_AMC_PLUS("AMC+"),
    AVAILABILITY_APPLE_CARD("Apple Card"),
    AVAILABILITY_APPLE_CARPLAY("Apple CarPlay"),
    AVAILABILITY_APPLE_PAY("Apple Pay"),
    //AVAILABILITY_APPLE_ONE("Apple One Bundle"),
    AVAILABILITY_APPLE_APP_STORE_APPS("Apple App Store: Apps"),
    AVAILABILITY_APPLE_APP_STORE_GAMES("Apple App Store: Games"),
    AVAILABILITY_APPLE_ARCADE("Apple Arcade"),
    AVAILABILITY_APPLE_MAPS_CONGESTION_ZONES("Apple Maps: Congestion Zones"),
    AVAILABILITY_APPLE_MAPS_DIRECTIONS("Apple Maps: Directions"),
    AVAILABILITY_APPLE_MAPS_SPEED_CAMERAS("Apple Maps: Speed Cameras"),
    AVAILABILITY_APPLE_MAPS_SPEED_LIMITS("Apple Maps: Speed Limits"),
    AVAILABILITY_APPLE_MAPS_NEARBY("Apple Maps: Nearby"),
    AVAILABILITY_APPLE_MUSIC("Apple Music"),
    AVAILABILITY_APPLE_SIRI("Apple Siri"),
    AVAILABILITY_APPLE_ITUNES_STORE_MOVIES("iTunes Store: Movies"),
    AVAILABILITY_APPLE_ITUNES_STORE_MUSIC("iTunes Store: Music"),
    //AVAILABILITY_APPLE_ITUNES_STORE_RINGTONES_AND_TONES("iTunes Store: Ringtones & Tones"),
    AVAILABILITY_APPLE_ITUNES_STORE_TV_SHOWS("iTunes Store: TV Shows"),
    AVAILABILITY_APPLE_TV_APP("Apple TV App"),
    AVAILABILITY_APPLE_TV_PLUS("Apple TV+"),
    //AVAILABILITY_APPLE_PODCASTS("Apple Podcasts"),
    AVAILABILITY_APPLE_NEWS("Apple News"),
    AVAILABILITY_APPLE_NEWS_AUDIO("Apple News Audio"),
    AVAILABILITY_APPLE_NEWS_PLUS("Apple News+"),
    //AVAILABILITY_APPLE_FITNESS_PLUS("Apple Fitness+"),
    AVAILABILITY_AT_AND_T_TV("AT&T TV"),
    AVAILABILITY_DAZN("DAZN"),
    AVAILABILITY_DISCOVERY_PLUS("Discovery+"),
    AVAILABILITY_DISNEY_PLUS("Disney+"),
    AVAILABILITY_ESPN_PLUS("ESPN+"),
    AVAILABILITY_GOOGLE_ASSISTANT("Google Assistant"),
    AVAILABILITY_GOOGLE_PAY("Google Pay"),
    AVAILABILITY_GOOGLE_PLAY_PASS("Google Play Pass"),
    AVAILABILITY_HBO_MAX("HBO Max"),
    AVAILABILITY_HULU("Hulu"),
    AVAILABILITY_NVIDIA_GEFORCE_NOW("NVIDIA GeForce NOW"),
    AVAILABILITY_PARAMOUNT_PLUS("Paramount+"),
    AVAILABILITY_PEACOCK("Peacock"),
    AVAILABILITY_PLAYSTATION_NOW("PlayStation Now"),
    AVAILABILITY_SAMSUNG_PAY("Samsung Pay"),
    AVAILABILITY_SHOWTIME("Showtime"),
    AVAILABILITY_SPOTIFY("Spotify"),
    AVAILABILITY_STADIA("Stadia"),
    AVAILABILITY_STARZ("Starz"),
    AVAILABILITY_STARZPLAY("Starzplay"),
    AVAILABILITY_TIDAL("Tidal"),
    AVAILABILITY_VENMO("Venmo"),
    AVAILABILITY_XBOX_CLOUD_GAMING("Xbox Cloud Gaming"),
    AVAILABILITY_XBOX_GAME_PASS("Xbox Game Pass"),
    AVAILABILITY_XBOX_LIVE("Xbox Live"),
    AVAILABILITY_YOUTUBE_PREMIUM("YouTube Premium"),
    AVAILABILITY_YOUTUBE_TV("YouTube TV"),

    GOVERNMENT_TYPE,

    INFO_AGE_STRUCTURE("Age Structure"),
    INFO_BLOOD_TYPE_DISTRIBUTION("Blood Type Distribution"),
    INFO_MEDIAN_AGE("Estimated Median Age"),
    INFO_MINIMUM_ANNUAL_LEAVE("Minimum Annual Leave"),
    INFO_MINIMUM_WAGE("Minimum Wage"),

    LEGALITY_ABORTION("Abortion"),
    LEGALITY_BITCOIN("Bitcoin"),
    LEGALITY_CANNABIS("Cannabis"),
    LEGALITY_DRINKING_AGE("Alcohol"),
    LEGALITY_DRUG_AYAHUASCA("Drug: Ayahuasca"),
    LEGALITY_DRUG_COCAINE("Drug: Cocaine"),
    LEGALITY_DRUG_IBOGAINE("Drug: Ibogaine"),
    LEGALITY_DRUG_METH("Drug: Meth"),
    LEGALITY_DRUG_PSILOCYBIN_MUSHROOMS("Drug: Psychedelic Mushrooms"),
    LEGALITY_DRUG_PSYCHOACTIVE_CACTUS("Drug: Psychedelic Cacti"),
    LEGALITY_DRUG_SALVIA_DIVINORUM("Drug: Salvia Divinorum"),
    LEGALITY_GUNS("Firearms"),
    LEGALITY_INCEST("Incest"),
    LEGALITY_MARITAL_RAPE("Marital Rape"),
    LEGALITY_PORNOGRAPHY("Adult Film"),
    LEGALITY_PROSTITUTION("Prostitution"),
    LEGALITY_SMOKING_AGE("Smoking"),

    NATIONAL_CAPITAL("National Capital"),

    RANKING_ADULT_HIV_PREVALENCE("Adult HIV Prevalence"),
    RANKING_CANNABIS_USE("Cannabis Use"),
    RANKING_CIVILIAN_FIREARMS("Civilian Firearms"),
    RANKING_CLIMATE_CHANGE_PERFORMANCE_INDEX("Climate Change Performance"),
    RANKING_CO2_EMISSIONS("CO2 Emissions"),
    RANKING_CORRUPTION_PERCEPTION_INDEX("Corruption Perception"),
    RANKING_DEMOCRACY_INDEX("Democracy"),
    RANKING_DIVORCE_RATE("Divorce Rate"),
    RANKING_ECONOMIC_FREEDOM_INDEX("Economic Freedom"),
    RANKING_EDUCATION_INDEX("Education"),
    RANKING_ELECTRICITY_CONSUMPTION("Electricity Consumption"),
    RANKING_FRAGILE_STATE_INDEX("Fragile State"),
    RANKING_FREEDOM_RANKINGS("Freedom"),
    RANKING_GLOBAL_PEACE_INDEX("Global Peace"),
    RANKING_GLOBAL_TERRORISM_INDEX("Global Terrorism"),
    RANKING_HOMICIDE_RATE("Homicide Rate"),
    RANKING_HUMAN_DEVELOPMENT_INDEX("Human Development"),
    RANKING_INCARCERATION_RATE("Incarceration Rate"),
    RANKING_INFANT_MORTALITY_RATE("Infant Mortality Rate"),
    RANKING_INFLATION_RATE("Inflation Rate"),
    RANKING_LEGATUM_PROSPERITY_INDEX("Prosperity"),
    RANKING_LIFE_EXPECTANCY("Life Expectancy"),
    RANKING_MATERNAL_MORTALITY_RATE("Maternal Mortality Rate"),
    RANKING_NATURAL_DISASTER_RISK("Natural Disaster Risk"),
    RANKING_OBESITY_RATE("Obesity Rate"),
    RANKING_POPULATION("Population"),
    RANKING_PRESS_FREEDOM_INDEX("Press Freedom"),
    RANKING_QUALITY_OF_LIFE_INDEX("Quality of Life"),
    RANKING_QUALITY_OF_NATIONALITY_INDEX("Quality of Nationality"),
    RANKING_SOCIAL_PROGRESS_INDEX("Social Progress"),
    RANKING_SUICIDE_RATE("Suicide Rate"),
    RANKING_UNEMPLOYMENT_RATE("Unemployment Rate"),
    RANKING_WORLD_GIVING_INDEX("Generosity"),
    RANKING_WORLD_HAPPINESS_REPORT("World Happiness"),

    SERVICE_APPLE_MAPS_FLYOVER("Flyover"),
    SERVICE_CIA_VALUES("CIA Values"),
    SERVICE_TRAVEL_BRIEFING("Travel Briefing"),
    SERVICE_WIKIPEDIA("Wikipedia"),

    CITIES,
    RESOURCES,
    TERRITORIES,

    VALUE_HEALTH_CARE_SYSTEM("Health Care System"),
    VALUE_MILITARY_ENLISTMENT_AGE("Military Enlistment Age"),
    VALUE_MINIMUM_DRIVING_AGE("Minimum Driving Age"),
    VALUE_SYSTEM_OF_GOVERNMENT("System of Government"),
    VALUE_TRAFFIC_SIDE("Side of traffic"),
    VALUE_VOTING_AGE("Voting Age"),
    ;

    private final String title;

    CountryInfo() {
        this(null);
    }
    CountryInfo(String title) {
        this.title = title;
    }

    @Override
    public String getTitle() {
        return title;
    }
}
